export type Question = {
  question: string;
  options: string[];
  answer: string;
  explanation: string;
};

export const allQuestions: Question[] = [
    { question: "India observes National Sports Day on whose birth anniversary?", options: ["Milkha Singh", "Mansoor Ali Khan Pataudi", "Dhyan Chand", "Michael Ferreira"], answer: "Dhyan Chand", explanation: "National Sports Day is celebrated on August 29th, the birthday of hockey legend Major Dhyan Chand, who is widely regarded as the greatest hockey player of all time." },
    { question: "Which country is called the “Sugar Bowl of the World”?", options: ["Cuba", "Italy", "India", "Japan"], answer: "Cuba", explanation: "Cuba earned the nickname 'Sugar Bowl of the World' because, for a long period, it was the largest producer and exporter of sugar globally, with its economy heavily reliant on it." },
    { question: "Avani Lekhara is famed for which sport?", options: ["Table Tennis", "Cycling", "Shooting", "Boxing"], answer: "Shooting", explanation: "Avani Lekhara is a celebrated Indian Paralympian who competes in rifle shooting. She made history by winning a gold medal at the Tokyo 2020 Paralympics." },
    { question: "Which port is known as the “Gateway of Eastern India”?", options: ["Kolkata Port", "Visakhapatnam Port", "Port Blair", "Paradip Port"], answer: "Kolkata Port", explanation: "The Kolkata Port (Syama Prasad Mookerjee Port) is called the 'Gateway of Eastern India' as it's a major riverine port serving the vast economic hinterland of eastern and north-eastern India." },
    { question: "A major classical dance of Andhra Pradesh is:", options: ["Kuchipudi", "Bharatanatyam", "Raaslila", "Bihu"], answer: "Kuchipudi", explanation: "Kuchipudi is a renowned classical dance form that originated in a village named Kuchipudi in the Krishna district of Andhra Pradesh, India." },
    { question: "Which inspiring slogan is attributed to Subhas Chandra Bose?", options: ["“Live as if you were to die tomorrow…”", "“Lose yourself in service…”", "“Give me blood and I will give you freedom.”", "“First they ignore you…”"], answer: "“Give me blood and I will give you freedom.”", explanation: "“Give me blood and I will give you freedom” (Tum Mujhe Khoon Do, Main Tumhe Azadi Dunga) was a powerful slogan used by Subhas Chandra Bose to motivate the soldiers of the Indian National Army (INA)." },
    { question: "The Swadeshi Movement began in response to the…", options: ["Partition of Bengal", "Khilafat Movement", "Formation of Muslim League", "Non-cooperation Movement"], answer: "Partition of Bengal", explanation: "The Swadeshi Movement was a major pre-independence movement started in 1905 as a direct protest against the British decision to partition Bengal." },
    { question: "How many Tirthankaras are there in Jainism?", options: ["12", "15", "24", "26"], answer: "24", explanation: "In Jainism, there are 24 Tirthankaras (spiritual teachers) in each half of the cosmic time cycle. Lord Mahavira was the 24th and last Tirthankara of the current era." },
    { question: "The Suez Canal connects which bodies of water?", options: ["Mediterranean & Red Sea", "Caspian & Aral Seas", "Red Sea & Nile River", "None of the above"], answer: "Mediterranean & Red Sea", explanation: "The Suez Canal is a crucial artificial sea-level waterway in Egypt that connects the Mediterranean Sea to the Red Sea, significantly shortening trade routes between Europe and Asia." },
    { question: "BrahMos is a type of…", options: ["Short-range supersonic cruise missile", "Air‑defence gun", "Military satellite", "Multiple rocket launcher"], answer: "Short-range supersonic cruise missile", explanation: "BrahMos is a supersonic cruise missile developed as a joint venture between India's DRDO and Russia's NPO Mashinostroyeniya. It can be launched from submarines, ships, aircraft, or land." },
    { question: "The term “Breaststroke” is used in which sport?", options: ["Football", "Swimming", "Cricket", "Lawn Tennis"], answer: "Swimming", explanation: "Breaststroke is one of the four main competitive swimming styles, characterized by the swimmer's chest being on the water and not rotated." },
    { question: "Who founded the Brahmo Samaj?", options: ["Keshab Chandra Sen", "Raja Rammohan Roy", "Devendranath Tagore", "Dayananda Saraswati"], answer: "Raja Rammohan Roy", explanation: "The Brahmo Samaj, a pivotal socio-religious reform movement, was founded in Calcutta in 1828 by Raja Rammohan Roy, a key figure in the Bengal Renaissance." },
    { question: "The Widow Remarriage Act (1856) was passed during the tenure of?", options: ["Lord Canning", "Lord Ripon", "Lord William Bentinck", "Lord Dalhousie"], answer: "Lord Dalhousie", explanation: "The Hindu Widows' Remarriage Act, 1856, was drafted during the tenure of Lord Dalhousie and was passed by his successor, Lord Canning." },
    { question: "In which year was the Suez Canal officially opened?", options: ["1856", "1869", "1875", "1882"], answer: "1869", explanation: "After a decade of construction, the Suez Canal was officially opened for navigation on November 17, 1869." },
    { question: "Which river names inspired the name “BrahMos”?", options: ["Brahmaputra & Moskva", "Brahmaputra & Sewaro", "Brahmaputra & Oswego", "Brahmaputra & Moreau"], answer: "Brahmaputra & Moskva", explanation: "The name BrahMos is a portmanteau formed from the names of two rivers: the Brahmaputra of India and the Moskva of Russia." },
    { question: "“Give me blood…” message was given in which region?", options: ["Tokyo", "Burma", "China", "London"], answer: "Burma", explanation: "Subhas Chandra Bose delivered this famous speech in 1944 in Burma (present-day Myanmar) to motivate the troops of the Indian National Army." },
    { question: "Who scored India’s first gold in Paralympics?", options: ["Deepa Malik", "Avani Lekhara", "Murlikant Petkar", "Devendra Jhajharia"], answer: "Murlikant Petkar", explanation: "While Avani Lekhara was the first Indian woman to win Paralympic gold, the first-ever Paralympic gold for India was won by Murlikant Petkar in swimming at the 1972 Heidelberg Games." },
    { question: "Which dance from Andhra shares its name with a village in Krishna district?", options: ["Kuchipudi", "Kathakali", "Odissi", "Mohiniyattam"], answer: "Kuchipudi", explanation: "The classical dance form of Kuchipudi is named after the village of its origin, Kuchipudi, which is located in the Krishna district of Andhra Pradesh." },
    { question: "Who is known as the “Wizard of Hockey”?", options: ["Balbir Singh", "Dhanraj Pillay", "Major Dhyan Chand", "Hemanta Lakra"], answer: "Major Dhyan Chand", explanation: "Major Dhyan Chand was nicknamed 'The Wizard' or 'The Magician' of hockey for his superb ball control and goal-scoring feats." },
    { question: "In what context was Bose's famous 'Give me blood...' slogan delivered in 1944?", options: ["GCC speech", "INA rally", "INA speech in Burma", "CWC meeting"], answer: "INA speech in Burma", explanation: "This slogan was the highlight of a motivational speech given by Netaji Subhas Chandra Bose to the soldiers of the Indian National Army (INA) in Burma in 1944." },
    { question: "Who was the first Indian woman to win an individual Olympic medal?", options: ["Karnam Malleswari", "Saina Nehwal", "P.V. Sindhu", "Sakshi Malik"], answer: "Karnam Malleswari", explanation: "Karnam Malleswari created history by winning a bronze medal in weightlifting at the 2000 Sydney Olympics, becoming the first Indian woman to win an Olympic medal." },
    { question: "What is the full form of DRDL?", options: ["Differential Research & Documentation Lab", "Defence Research and Development Laboratory", "Department of Research & Development Lab", "None of the above"], answer: "Defence Research and Development Laboratory", explanation: "DRDL stands for Defence Research and Development Laboratory. It is a premier laboratory of DRDO located in Hyderabad, working on missile systems." },
    { question: "Which country launched the world’s first 5G network?", options: ["Japan", "China", "South Korea", "USA"], answer: "South Korea", explanation: "In April 2019, South Korea became the first country in the world to launch a nationwide commercial 5G (fifth-generation) wireless network." },
    { question: "What is the weak zone of the Earth's crust called?", options: ["Seismic zone", "Cosmic zone", "Formic zone", "Anaemic zone"], answer: "Seismic zone", explanation: "A seismic zone, or fault zone, is an area of the Earth's crust where tectonic plates meet. These zones are prone to earthquakes and other seismic activities." },
    { question: "India’s first national museum of Indian cinema is located in:", options: ["Delhi", "Hyderabad", "Rajasthan", "Mumbai"], answer: "Mumbai", explanation: "The National Museum of Indian Cinema (NMIC) is located in Mumbai, the city that is the heart of India's film industry, often known as Bollywood." },
    { question: "Who was honoured with the Bharat Ratna in 2019?", options: ["Lata Mangeshkar", "Asha Bhosle", "Bhupen Hazarika", "Manna Dey"], answer: "Bhupen Hazarika", explanation: "In 2019, India's highest civilian award, the Bharat Ratna, was conferred upon social activist Nanaji Deshmukh (posthumously), singer-composer Bhupen Hazarika (posthumously), and former President Pranab Mukherjee." },
    { question: "Which state recently generated over one crore ABHA health account IDs?", options: ["Bihar", "Haryana", "Madhya Pradesh", "Uttar Pradesh"], answer: "Uttar Pradesh", explanation: "Uttar Pradesh achieved a significant milestone in the Ayushman Bharat Digital Mission by creating over one crore ABHA (Ayushman Bharat Health Account) IDs." },
    { question: "Which Kerala district formed a committee to tackle water hyacinth?", options: ["Kottayam", "Kannur", "Wayanad", "Thrissur"], answer: "Kottayam", explanation: "The Kottayam district administration in Kerala often forms committees and initiatives to manage the menace of the invasive water hyacinth in its famous backwaters and Vembanad lake." },
    { question: "What is India's approximate rank in the 2025 SDG Index?", options: ["77th", "88th", "95th", "99th"], answer: "99th", explanation: "This refers to a projected ranking for India in the Sustainable Development Goals (SDG) Index, which tracks progress on goals set by the UN related to poverty, health, and equality." },
    { question: "Which state won the tableau prize at Republic Day Parade 2025?", options: ["Madhya Pradesh", "Maharashtra", "Uttar Pradesh", "Rajasthan"], answer: "Uttar Pradesh", explanation: "This question is based on a projection or a hypothetical scenario, as the 2025 parade has not yet occurred. Uttar Pradesh has been a frequent winner in recent years." },
    { question: "Which country developed the first deep-sea radar to detect high-flying aircraft?", options: ["USA", "Russia", "China", "Japan"], answer: "China", explanation: "Chinese scientists have claimed to develop a new type of radar technology that can detect stealth aircraft at considerable distances, a significant technological claim." },
    { question: "Which national leader edited the Marathi newspaper Kesari?", options: ["Gopal Krishna Gokhale", "Dr. B.R. Ambedkar", "M.G. Ranade", "Bal Gangadhar Tilak"], answer: "Bal Gangadhar Tilak", explanation: "Kesari is a Marathi newspaper founded in 1881 by Lokmanya Bal Gangadhar Tilak, a prominent leader of the Indian Independence movement. He used it to voice nationalist sentiments." },
    { question: "Which metal is extracted by smelting?", options: ["Aluminium", "Magnesium", "Iron", "Silver"], answer: "Iron", explanation: "Smelting is a process of applying heat to an ore to extract a base metal. It is most prominently used to produce iron from its ore (iron oxide) in a blast furnace." },
    { question: "What is the formula of calcium hydroxide?", options: ["CaOH₂", "Ca₂OH", "Ca(OH)₂", "CaOH"], answer: "Ca(OH)₂", explanation: "The correct chemical formula for calcium hydroxide is Ca(OH)₂, representing one calcium ion (Ca²⁺) bonded to two hydroxide ions (OH⁻)." },
    { question: "What is India’s ranking in the Global Firepower Index 2025?", options: ["2nd", "3rd", "4th", "5th"], answer: "4th", explanation: "India consistently ranks as the 4th most powerful military in the world according to the Global Firepower Index, which assesses military strength based on multiple factors." },
    { question: "Which international body did the US withdraw funding from under Trump, targeting Palestinian refugee aid?", options: ["UN Human Rights Council", "WHO", "UNRWA", "UNDP"], answer: "UNRWA", explanation: "The Trump administration cut all funding to UNRWA (The United Nations Relief and Works Agency for Palestine Refugees in the Near East), which is the specific UN agency for Palestinian refugees." },
    { question: "When is India expected to receive its fourth squadron of Russian S-400 systems?", options: ["2024", "2025", "2026", "2027"], answer: "2025", explanation: "This refers to the projected delivery timeline for the remaining squadrons of the S-400 Triumf air defence missile systems from Russia to India." },
    { question: "How many AK-203 rifles will the Indian Army receive in 2025?", options: ["50,000", "70,000", "90,000", "100,000"], answer: "70,000", explanation: "This number refers to a batch of rifles being produced under the 'Make in India' initiative through an Indo-Russian joint venture to equip the Indian Army." },
    { question: "Where is the Army Airborne Training School located?", options: ["Agra", "Mumbai", "Pune", "Nagpur"], answer: "Agra", explanation: "The Indian Army's Airborne Training School (AATS), which trains paratroopers, is located in Agra, Uttar Pradesh." },
    { question: "Which country will become the 32nd NATO member?", options: ["Qatar", "Oman", "Hungary", "Sweden"], answer: "Sweden", explanation: "Sweden officially joined the North Atlantic Treaty Organization (NATO) in March 2024, becoming its 32nd member." },
    { question: "What does INTERPOL stand for?", options: ["International Criminal Pole", "International Create Police", "International Criminal Police Organization", "None"], answer: "International Criminal Police Organization", explanation: "INTERPOL stands for the International Criminal Police Organization. It is an inter-governmental organization facilitating worldwide police cooperation." },
    { question: "Ex ‘Varuna’ is a bilateral exercise between India and which country?", options: ["Japan", "Sri Lanka", "France", "Australia"], answer: "France", explanation: "'Varuna' is the name of the long-standing bilateral naval exercise conducted between the Indian Navy and the French Navy." },
    { question: "What does AEW&C stand for?", options: ["Airborne Early Warning and Center System", "Airborne East Warning and Control System", "Airborne Early Warning and Control System", "None of the above"], answer: "Airborne Early Warning and Control System", explanation: "AEW&C stands for Airborne Early Warning and Control System. It is an airborne radar picket system designed to detect aircraft, ships and vehicles at long ranges." },
    { question: "Which day is observed as Kokborok Day in Tripura?", options: ["Jan 18", "Jan 19", "Jan 20", "Jan 21"], answer: "Jan 19", explanation: "Kokborok Day is observed in the state of Tripura on January 19th every year to celebrate the development of Kokborok as an official language." },
    { question: "What is the theme of the tri-services tableau for Republic Day 2025?", options: ["United India, Strong India", "Shashakt aur Surakshit Bharat", "India’s Defence Heritage", "Bharat’s Joint Defence Vision"], answer: "Shashakt aur Surakshit Bharat", explanation: "This is a projected theme. 'Shashakt aur Surakshit Bharat' (Strong and Secure India) reflects the focus on national security and indigenous defence capabilities." },
    { question: "PM JANMAN scheme is associated with which group?", options: ["MSME Owners", "Farmers", "Particularly Vulnerable Tribal Groups", "NRIs"], answer: "Particularly Vulnerable Tribal Groups", explanation: "The PM-JANMAN (Pradhan Mantri Janjati Adivasi Nyaya Maha Abhiyan) scheme is a central government initiative aimed at the socio-economic development of Particularly Vulnerable Tribal Groups (PVTGs)." },
    { question: "Which country pulled out of the Paris Climate Agreement?", options: ["France", "Germany", "USA", "None"], answer: "USA", explanation: "The United States, under the Trump administration, formally withdrew from the Paris Agreement on climate change in 2020. It has since rejoined." },
    { question: "Which three states received full statehood on 21 Jan 1972?", options: ["Nagaland, Manipur, Tripura", "Tripura, Manipur, Meghalaya", "Assam, Manipur, Mizoram", "Sikkim, Meghalaya, Tripura"], answer: "Tripura, Manipur, Meghalaya", explanation: "On January 21, 1972, Tripura, Manipur, and Meghalaya became full-fledged states under the North Eastern Region (Re-organisation) Act, 1971." },
    { question: "Who authored The World after Gaza?", options: ["Arundhati Roy", "Pankaj Mishra", "Chetan Bhagat", "Shashi Tharoor"], answer: "Pankaj Mishra", explanation: "Pankaj Mishra is a renowned Indian essayist and novelist who writes extensively on politics and literature. 'The World after Gaza' is one of his notable works." },
    { question: "Which country became a BRICS partner state recently?", options: ["Nigeria", "Saudi Arabia", "Iran", "Argentina"], answer: "Saudi Arabia", explanation: "In January 2024, Saudi Arabia, along with Egypt, UAE, Iran, and Ethiopia, officially joined the BRICS group of emerging economies." },
    { question: "What weapon counters swarm drones?", options: ["Bhargavastra", "Agni", "Vayu", "Saryu"], answer: "Bhargavastra", explanation: "Project Bhargavastra is reportedly an indigenous anti-drone system being developed by India's DRDO to detect, track, and neutralize hostile drone swarms." },
    { question: "Which day is National Milk Day observed?", options: ["Dec 25", "Dec 26", "Nov 26", "Nov 25"], answer: "Nov 26", explanation: "India celebrates National Milk Day on November 26th to commemorate the birth anniversary of Dr. Verghese Kurien, the 'Father of the White Revolution in India'." },
    { question: "Who is called the ‘Father of Green Revolution in India’?", options: ["M.S. Swaminathan", "Verghese Kurien", "Vikram Sarabhai", "Norman Borlaug"], answer: "M.S. Swaminathan", explanation: "Dr. M.S. Swaminathan, an eminent agricultural scientist, is hailed as the 'Father of the Green Revolution in India' for his leadership in introducing high-yielding varieties of wheat and rice." },
    { question: "Who founded the Indian National Army (INA)?", options: ["Subhas Chandra Bose", "Rash Bihari Bose", "Capt Mohan Singh", "Major Fujiwara"], answer: "Capt Mohan Singh", explanation: "The first Indian National Army (INA) was conceptualized and founded by Captain Mohan Singh in 1942 in Southeast Asia during WWII. It was later revived and led by Subhas Chandra Bose." },
    { question: "What does the “Blue Revolution” refer to?", options: ["Fish production", "Food grain production", "Oil production", "Milk production"], answer: "Fish production", explanation: "The 'Blue Revolution' refers to the emergence of aquaculture as a significant and highly productive agricultural activity. It is focused on increasing fish production." },
    { question: "The Territorial Army was established in which year?", options: ["1962", "1949", "1920", "1953"], answer: "1949", explanation: "The Territorial Army (TA), a second line of defence after the Regular Indian Army, was formally inaugurated by the first Indian Governor-General, C. Rajagopalachari, on October 9, 1949." },
    { question: "How many Vedas are there in Hinduism?", options: ["2", "3", "4", "5"], answer: "4", explanation: "There are four Vedas in Hinduism: the Rigveda, the Samaveda, the Yajurveda, and the Atharvaveda. They are the oldest scriptures of Hinduism." },
    { question: "Where was Gautam Buddha born?", options: ["Kushinagar", "Lumbini", "Bodh Gaya", "Sarnath"], answer: "Lumbini", explanation: "Gautam Buddha was born in Lumbini, which is located in modern-day Nepal. Bodh Gaya is where he attained enlightenment, and Sarnath is where he gave his first sermon." },
    { question: "Who founded the Gupta dynasty?", options: ["Samudragupta", "Chandragupta I", "Kumaragupta", "Skandagupta"], answer: "Chandragupta I", explanation: "The Gupta dynasty was founded by Chandragupta I, who established a powerful empire in ancient India. Samudragupta was his son and a great conqueror." },
    { question: "Which planet is called the 'Red Planet'?", options: ["Mercury", "Mars", "Saturn", "Venus"], answer: "Mars", explanation: "Mars is called the 'Red Planet' because of the reddish iron oxide prevalent on its surface, which gives it a distinct reddish appearance." }
];

const sampleQuestion: Question = {
  question: "This is a sample question number X. What is the correct option?",
  options: ["Sample Option A", "Sample Option B", "This is the Correct Answer", "Sample Option D"],
  answer: "This is the Correct Answer",
  explanation: "This is the detailed explanation for why the chosen option is the correct answer for sample question X."
};

for (let i = allQuestions.length + 1; i <= 200; i++) {
    allQuestions.push({
        ...sampleQuestion,
        question: `This is a sample question number ${i}. What is the correct option?`,
        explanation: `This is the detailed explanation for why the chosen option is the correct answer for sample question ${i}.`
    });
}
