
import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-slate-50 min-h-screen">
      <header className="sticky-header bg-white/80 backdrop-blur-lg shadow-sm">
        <nav className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link href="/" className="font-heading uppercase tracking-wider text-2xl text-foreground">
            Agniveer Ascent
          </Link>
          <Link href="/" className="solid-button font-bold py-2 px-4 rounded-lg text-sm">
            &larr; Back to Home
          </Link>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
          <h1 className="text-4xl font-heading font-bold mb-4">Privacy Policy for Agniveer Ascent</h1>
          <p className="text-muted-foreground mb-8">Last updated: July 01, 2025</p>

          <p className="mb-6">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mb-6">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
          <h3 className="text-2xl font-bold mt-4 mb-2">Interpretation</h3>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-2xl font-bold mt-4 mb-2">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-4 mb-6">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to agniveer ascent.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Rajasthan, India</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to agniveer ascent, accessible from <Link href="https://agniveerquiz.netlify.app/" className="text-primary hover:underline">https://agniveerquiz.netlify.app/</Link></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
          <h3 className="text-2xl font-bold mt-4 mb-2">Types of Data Collected</h3>
          <h4 className="text-xl font-semibold mt-4 mb-2">Personal Data</h4>
          <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside space-y-2 mb-6">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-xl font-semibold mt-4 mb-2">Usage Data</h4>
          <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <p className="mb-6">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
          
          <h4 className="text-xl font-semibold mt-4 mb-2">Tracking Technologies and Cookies</h4>
           <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
          <ul className="list-disc list-inside space-y-4 mb-6">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
          </ul>
          <p className="mb-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
          <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul className="list-disc list-inside space-y-4 mb-6">
            <li>
              <p><strong>Necessary / Essential Cookies</strong></p>
              <p>Type: Session Cookies</p>
              <p>Administered by: Us</p>
              <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            </li>
            <li>
              <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
              <p>Type: Persistent Cookies</p>
              <p>Administered by: Us</p>
              <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </li>
            <li>
              <p><strong>Functionality Cookies</strong></p>
              <p>Type: Persistent Cookies</p>
              <p>Administered by: Us</p>
              <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </li>
          </ul>

          <h3 className="text-2xl font-bold mt-4 mb-2">Use of Your Personal Data</h3>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-4 mb-6">
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract.</li>
            <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers and general information.</li>
            <li>To manage Your requests: To attend and manage Your requests to Us.</li>
            <li>For business transfers: We may use Your information to evaluate or conduct a merger or other transfer of Our assets.</li>
            <li>For other purposes, such as data analysis, identifying usage trends, and improving our Service.</li>
          </ul>

          <h3 className="text-2xl font-bold mt-4 mb-2">Sharing Your Personal Information</h3>
          <p className="mb-4">We may share Your personal information in the following situations:</p>
          <ul className="list-disc list-inside space-y-4 mb-6">
            <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service.</li>
            <li><strong>For business transfers:</strong> In connection with any merger, sale of Company assets, or acquisition.</li>
            <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates.</li>
            <li><strong>With business partners:</strong> To offer You certain products, services or promotions.</li>
            <li><strong>With other users:</strong> When you interact in public areas, your information may be viewed by all users.</li>
            <li><strong>With Your consent:</strong> For any other purpose with Your consent.</li>
          </ul>
          
          <h3 className="text-2xl font-bold mt-4 mb-2">Retention of Your Personal Data</h3>
          <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. </p>

          <h3 className="text-2xl font-bold mt-4 mb-2">Transfer of Your Personal Data</h3>
          <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

          <h3 className="text-2xl font-bold mt-4 mb-2">Delete Your Personal Data</h3>
          <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

          <h3 className="text-2xl font-bold mt-4 mb-2">Disclosure of Your Personal Data</h3>
          <h4 className="text-xl font-semibold mt-4 mb-2">Business Transactions</h4>
          <p className="mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>
          <h4 className="text-xl font-semibold mt-4 mb-2">Law enforcement</h4>
          <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law.</p>
          <h4 className="text-xl font-semibold mt-4 mb-2">Other legal requirements</h4>
          <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: Comply with a legal obligation, Protect and defend the rights or property of the Company, Prevent or investigate possible wrongdoing, Protect the personal safety of Users, or Protect against legal liability.</p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Security of Your Personal Data</h2>
          <p className="mb-6">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Children's Privacy</h2>
          <p className="mb-6">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Links to Other Websites</h2>
          <p className="mb-6">Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Changes to this Privacy Policy</h2>
          <p className="mb-6">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

          <h2 className="text-3xl font-heading font-semibold mt-8 mb-4">Contact Us</h2>
          <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>By email: <a href="mailto:rcwcaps@gmail.com" className="text-primary hover:underline">rcwcaps@gmail.com</a></li>
          </ul>
        </div>
      </main>
    </div>
  );
}
